export const CONFIGURATION_PROVIDER_TOKENS = {
  // JWT Services
  JWT_ACCESS_TOKEN_SERVICE: 'JWT_ACCESS_TOKEN_SERVICE',
  JWT_REFRESH_TOKEN_SERVICE: 'JWT_REFRESH_TOKEN_SERVICE',

  REDIS_CONFIG: 'REDIS_CONFIG',
  CLOUDINARY_CONFIG: 'CLOUDINARY_CONFIG',
  DATABASE_CONFIG: 'DATABASE_CONFIG',
} as const

export type ConfigurationProvider = (typeof CONFIGURATION_PROVIDER_TOKENS)[keyof typeof CONFIGURATION_PROVIDER_TOKENS]
