export const VERIFICATION_CODE_TYPES = {
  REGISTER: 'REGISTER',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  DISABLE_2FA: 'DISABLE_2FA',
}

export type VerificationCodeType = (typeof VERIFICATION_CODE_TYPES)[keyof typeof VERIFICATION_CODE_TYPES]
